#define HOLD_ON_OTHER_KEY_PRESS
#define TAPPING_TERM 1000
#define COMBO_TERM 35
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_STRICT_TIMER
#define DYNAMIC_MACRO_NO_NESTING
#define CAPS_WORD_IDLE_TIMEOUT 0
